services:
  postgres:
    image: postgres:16-alpine  # Используем alpine для скорости и 16 версию
    restart: always
    shm_size: 128mb
    ports:
      - '5433:5432'
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Для 16 версии работает старый путь

    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  echonotify:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      - ENVIRONMENT=docker
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

volumes:
  postgres_data: