"""add orders tables

Revision ID: b8c9d4e5f6a7
Revises: 7a7453e3135f
Create Date: 2025-12-21 11:35:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8c9d4e5f6a7'
down_revision: Union[str, None] = '7a7453e3135f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Orders',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('created_ad', sa.DateTime(), nullable=False),
        sa.Column('price', sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Orders_id'), 'Orders', ['id'], unique=False)

    op.create_table('UsersOrders',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('order_id', sa.Integer(), nullable=False),
        sa.Column('delivery_status', sa.Enum('PENDING', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='orderstatus'), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['order_id'], ['Orders.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_UsersOrders_id'), 'UsersOrders', ['id'], unique=False)
    op.create_index(op.f('ix_UsersOrders_order_id'), 'UsersOrders', ['order_id'], unique=False)
    op.create_index(op.f('ix_UsersOrders_user_id'), 'UsersOrders', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_UsersOrders_user_id'), table_name='UsersOrders')
    op.drop_index(op.f('ix_UsersOrders_order_id'), table_name='UsersOrders')
    op.drop_index(op.f('ix_UsersOrders_id'), table_name='UsersOrders')
    op.drop_table('UsersOrders')
    op.drop_index(op.f('ix_Orders_id'), table_name='Orders')
    op.drop_table('Orders')
    sa.Enum(name='orderstatus').drop(op.get_bind())
    # ### end Alembic commands ###
